---
title: "Trabalho Grupo 6 - O Uso da Midia Social no Ensino Superior"
author: Bruna Passerani, Guilherme Fuentes, Priscila da Rocha, Vittoria Zago, Winea
  Pasquareli
date: "13 de novembro de 2018"
output:
  pdf_document: default
  word_document: default
mainfont: Arial
fontsize: 12pt
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(readxl)) install.packages('readxl')
library(readxl)
df <- read_xlsx("C:/Grupo-6/dados/umses_graduacao_2018_vtidy.xlsx", sheet="dados")
```


##  Introducao
  Este trabalho tem como objetivo estudar os dados e levantar assim informações sobre o uso das mídias sociais nos discentes da instituição de nível superior UNESP em Bauru, SP. Através da ciência de dados, procuramos descobrir a relevância da mídia social para essa população: quais são mais usadas, por quanto tempo, com qual finalidade, e quais características influenciam nesse resultado. 
  Com esse resultado, informações valiosas podem ser extraídas e usadas estrategicamente, pelos professores ao conseguirem melhor propagação do conteúdo ensinado por exemplo, ou empresas de marketing atingirem melhores resultados ao investir mais em uma rede social.
  Nos próximos capítulos, veremos uma análise sobre as ferramentas e técnicas utilizadas, além das representações gráficas dos estudos realizados.

## Fundamentacao Teorica

### R
  Desenvolvido pelos estat?sticos Ross Ihaka e Robert Gentleman na d?cada de 90, o R ? considerado  uma linguagem e tamb?m um ambiente utilizado para desenvolver an?lises estat?sticas, e produzir gr?ficos. IBPAD (2017) relata que o software R fornece uma grande variedade de an?lises como : "modelagem linear e n?o-linear, testes estat?sticos cl?ssicos, an?lise de s?ries temporais, classifica??o, agrupamento, entre outros".

 O software se destaca por uma ampla possibilidade de codifica??o de c?lculos, matrizes, e fun??es, al?m disso, possui um extenso mecanismo para armazenar os dados que ser?o filtrados pelo programador atrav?s da ferramenta. O programa pode ser utilizado para coletar, armazenar e analisar dados de diferentes ?reas, ? poss?vel criar gr?ficos com dados estat?sticos por exemplo do painel eleitoral do nosso pa?s, ou at? mesmo a cria??o de mapas financeiros utilizando gr?ficos de pizza, barras entre outros (IBPAD, 2017).

  Uma de suas vantagem ? o fato de ser um software de c?digo aberto(open source), ou seja, possibilita que qualquer pessoa possa utiliz?-lo, al?m disso este programa vem ganhando destaque entre pesquisadores, engenheiros e profissionais do ramo estat?stico, tamb?m cont?m diversos pacotes que incrementam as suas funcionalidades, fazendo com que cres?a cada vez mais, ? poss?vel fazer seu download em diferentes plataformas como : windows, linux e mac.


### R Markdown
  R Markdown foi projetado com o intuito de facilitar a reprodutibilidade, já que tanto o código de computação quanto as narrativas (parte textual) estão no mesmo documento, no qual os resultados são gerados automaticamente a partir do código-fonte. 
  A maneira usual de compilar um documento R Markdown é clicar no botão “Knit” sendo o atalho de teclado correspondente é Ctrl + Shift + K, após clicar na opção o RStudio chama a função rmarkdown :: render () para renderizar o documento em uma nova sessão R, a reprodutibilidade é a principal razão pela qual o RStudio usa uma nova  sessão do R para renderizar seus documentos Rmd: na maioria dos casos, o usuário quer que seus documentos continuem a funcionar da próxima vez que for utilizar o R em ambientes de computação de outras pessoas.
  Existem dois tipos de formatos de saída no pacote rmarkdown: documentos e apresentações. Todos os formatos disponíveis estão listados abaixo:

Apresentação beamer
Apresentação ioslides
Apresentação em powerpoint
Apresentação slidy
Documento github
Documento HTML
Documento pdf
Documento do Word
Documento latex
Documento MD
Documento ODT
Documento RTF

### Github

  Git é um sistema de controle de versões distribuído que foi criado por Linus Torvalds em 2005. Um sistema de controle de versões pode ser definido como um software que mantém um registro com as alterações realizadas em determinado projeto ou arquivo ao longo do tempo. Por ser distribuído, todos os integrantes de um projeto possuem acesso a todo o histórico de versões deste e não apenas de seu estado atual. A ideia de sua criação surgiu quando Torvalds e os demais desenvolvedores do kernel Linux decidiram não utilizar mais o software controlador de versões BitKeeper após o detentor dos direitos autorais deste, Larry Macvoy, remover o acesso gratuito à ferramenta. 
  Como Torvalds desejava uma ferramenta semelhante ao BitKeeper para auxiliar no desenvolvimento do kernel do Linux, decidiu desenvolver seu próprio sistema controlador de versões, criando, assim, o Git. Por conta de sua velocidade e praticidade, o Git obteve sucesso e conseguiu diversos usuários pelo mundo.
  O GitHub é um site que permite a seus usuários a hospedagem de uma cópia de repositórios Git. Além disso, ele também possibilita a colaboração de integrantes de um grupo para desenvolver um projeto por possuir um local centralizado para compartilhar um repositório, interface web para visualizá-lo e também recursos como forking, pull, requests, issues e wikis que permite discussões, revisões e alterações no projeto junto à equipe de forma eficiente.

## UNESP

##Dados Censitarios
  Na pesquisa realizada tivemos a participação da seguinte proporção de público feminino e masculino:
### Gênero
### 1.Prefiro não declarar
### 2.Masculino e 
### 3.Feminino
sexo=table(df$genero)
sexo

lbls <- c("Masculino", "Feminino")

pct <- round(sexo/sum(sexo)*100, digits=1)
pct

lbls <- paste0(pct,"% ", lbls) # add percents to labels
lbls
png(filename="graficos/Genero.png", width = 800, height = 500, pointsize = 16)
par(bg = "bisque")

### Geração do gráfico tipo pizza (pie)
pie(sexo, labels = lbls, edges = 100, angle = 45, col = c("deepskyblue","darkviolet", "green3"), main = "Genero dos participantes")

dev.off()

  Conforme mostrado na figura tivemos participação de 60,7% publico masculino e 39,3% de publico feminino.

  A faixa etária dos participantes foi a seguinte:
## Faixa Etaria
### 1. Entre 16 e 20 anos
### 2. Entre 21 e 25 anos
### 3. Entre 26 e 30 anos
### 4. Entre 30 e 35 anos
### 5. Entre 36 e 40 anos
### 6. Acima de 40 anos

idade=table(df$idade)
idade
rotulos <- c("Entre 16 e 20 anos", "Entre 21 e 25 anos", "Entre 26 e 30 anos", 
"Entre 30 e 35 anos","Entre 36 e 40 anos", "6. Acima de 40 anos")
porc_Idade <- round(idade/sum(idade)*100, digits=1)
porc_Idade

png(filename="graficos/Idade.png", width = 800, height = 500, pointsize = 16)


par(bg = "bisque")

### Geração do gráfico tipo barra (barplot)
my_bar=barplot(idade, border=F, names.arg = NA, las=2,
               col = c("green","deepskyblue", "yellow", "red","purple", "pink"),
               ylab = "Quantidade",
               xlab = "Faixa Etaria",
               ylim = c(0,80),
               main = "Idade dos Participantes")

text(my_bar, idade+4, paste("n = ",idade,sep=""),cex=1) 


legend("topleft", legend = c("Entre 16 e 20 anos", "Entre 21 e 25 anos", "Entre 26 e 30 anos", "Entre 30 e 35 anos",
        "Entre 36 e 40 anos", "6. Acima de 40 anos"),
       col = c("green","deepskyblue", "yellow", "red","purple", "pink"),
       bty = "n", pch=20 , pt.cex = 2, cex = 0.8, 
       horiz = FALSE, inset = c(0.05, 0.05))

dev.off()

  Apos análise grafica temos que 42,6% dos participantes pertenciam à faixa etária entre 16 e 20 anos, 52,5% na faixa etária entre 21 e 25 anos e 4,9% na faixa etária entre 26 e 30 anos. A faixa etária dos participantes tem grande impacto para a pesquisa pois é composta da proxima geração ingressante no Ensino Superior etambém daqueles que a estão cursando neste momento. As mídias sociais estão presentes na vida dos estudantes do ensino superior e alguns estudos apontaram que grande parte destes estudantes usam as mídias sociais para interação com outros usuários e para construção de relacionamentos.
  
  ##Situacao Trabalhista
  A seguir dados sobre situa??o trabalista dos participantes:
  
trabalha=table(df$trabalha)
trabalha
rot <- c("Desempregado", "Jornada parcial", "Jornada integral", "Estagi?rio",
             "Trabalha por conta pr?pria", "Afastado temporariamente", "Aposentado", "Bolsista Capes")
porc_Trabalha <- round(trabalha/sum(trabalha)*100, digits=1)
porc_Trabalha
png(filename="graficos/Trabalha.png", width = 800, height = 500, pointsize = 16)

# Definindo a cor de fundo do gráfico
par(bg = "bisque")

# Geração do gráfico tipo barra (barplot)
my_bar=barplot(trabalha, border=F, names.arg = NA, las=2,
               col = c("green","deepskyblue", "yellow", "red","purple", "pink", "red","blue"),
               ylab = "Quantidade",
               xlab = "Status",
               ylim = c(0,80),
               main = "Situacao Trabalhista dos Participantes")
# Adicionando o texto a ser exibido 
text(my_bar, trabalha+4, paste("n = ",trabalha,sep=""),cex=1) 

#Agora adicionando a legenda ao gráfico
legend("topleft", legend = c("Desempregado", "Jornada parcial", "Jornada integral", "Estagi?rio",
        "Trabalha por conta pr?pria", "Afastado temporariamente", "Aposentado", "Bolsista Capes"),
       col = c("green","deepskyblue", "yellow", "red","purple", "pink", "red","blue"),
       bty = "n", pch=20 , pt.cex = 2, cex = 0.8, 
       horiz = FALSE, inset = c(0.05, 0.05))


dev.off()
  

 Também foi levantado o estado civil dos participantes, onde apenas 1.6% dos participantes se declararam casados, e os outros 98.4% como solteiros. 
## Estado Civil
### Dicionário de dados
### 1. Solteiro (a)
### 2. Casado (a)
### 3. União Estável
### 4. Viúvo (a)
### 5. Separado (a)
### 6. Prefiro não declarar
estadocivil=table(df$estadocivil)
estadocivil

lbls <- c("solteiro", "casado", "uniao", "viuvo", "separado", "naodeclara")

pct <- round(estadocivil/sum(estadocivil)*100, digits=1)
pct

lbls <- paste0(pct,"% ", lbls) # add percents to labels
lbls
png(filename="graficos/EstadoCivil.png", width = 800, height = 500, pointsize = 16)
par(bg = "bisque")

### Geração do gráfico tipo pizza (pie)
pie(estadocivil, labels = lbls, edges = 100, angle = 45, col = c("deepskyblue","darkviolet", "green3"), main = "Estado Civil dos participantes")

dev.off()

  Quanto a quantidade de filhos, 100% dos participantes declararam não ter nenhum filho, o que se mostra bem coerente com os participantes onde mais de 95% está abaixo dos 25 anos e quase 95% como solteiros. Já foi comprovado que as mulheres com maior nível de escolaridade, postergam mais seus filhos e diminuem a taxa de fecundidade, além disso, no Brasil é mais comum ter filhos após o casamento.
  ## Dicionário de dados
### 1. Sem filhos
### 2. Um filho
### 3. Dois filhos
### 4. Três filhos
### 5. Mais de três filhos

temfilhos=table(df$filhos)
temfilhos
lbls <- c("Sem Filhos", "Um", "Dois", "Tres", "Mais de Três Filhos")
porc_temfilhos <- round(temfilhos/sum(temfilhos)*100, digits=1)
porc_temfilhos
png(filename="graficos/TemFilhos.png", width = 800, height = 500, pointsize = 16)
par(bg = "bisque")

lbls <- paste0(porc_temfilhos,"% ", lbls) # add percents to labels
lbls


### Geração do gráfico tipo pizza (pie)
pie(temfilhos, labels = lbls, edges = 100, angle = 45, 
    col = c("deepskyblue","darkviolet", "green3"), main = "Quantidade de filhos dos participantes")

dev.off()

  Também foi questionado a faixa etária dos filhos, mas como nenhum participante declarou ter filhos, essa análise não foi representada gráficamente. Lembrando que não possuir filhos se mostra mais comum nessa população, o que pode influenciar no tempo que eles passam nas mídias, ou se estão solteiros quais mídias eles usam mais. Assim como se tivesse a faixa etária dos filhos declarada, poderia influenciar no tempo dedicado nas mídias dependendo da idade do filho.
  
# Opiniao sobre uso das midias sociais no ensino

    Nesta pesquisa, foram levantados dados sobre o uso das redes sociais como uma ferramenta que pode ser usada pelos professores da universidade, 62.3%  declaram que as redes devem ser utilizadas como ferramenta dos professores entretanto, 1.6% dizem que nao deveria ser utilizada como auxilio do professor, 31.1% dos entrevistados declaram que sim porem com restri??es e por fim 4.9% disseram n?o haver uma opni?o formada sobre o assunto discutido.
    
### 1. N?o
### 2. Sim
### 3. Sim, porem com restri??es
### 4. N?o tenho opni?o

academico=table(df$usoacademico)
academico

lbls <- c("N?o", "Sim", "Sim, com restri??o", "Sem opni?o")

porcentagem_academico <- round(academico/sum(academico)*100, digits=1)
porcentagem_academico


lbls <- paste0(porcentagem_academico,"% ", lbls) # add percents to labels
lbls
png(filename="graficos/UsoAcademico.png", width = 800, height = 500, pointsize = 16)
par(bg = "bisque")


### Geração do gráfico tipo pizza (pie)
pie(academico, labels = lbls, edges = 100, angle = 45, col = c("red","darkviolet", "blue", "pink"), main = "Midias sociais como ferramenta do professor")

dev.off()

Foram adquiridos também dados referentes à opnião dos participantes sobre a utilização das mídias sociais como forma de os professores se aproximarem de seus alunos. O resultado, como visto no gráfico a seguir, demonstra que 37.7% dos participantes concordam em utilizar as redes sociais como uma forma de os professores se paroximarem de seus alunos, 36.1% não concordam e 26.2% não possuem opinião a respeito dessa questão.

### 1. Nao
### 2. Sim
### 4. Nao sei/Nao tenho opniao

prof=table(df$profchegaal)
prof

lbls <- c("Nao", "Sim", "Nao sei/Nao tenho opiniao")

porcentagem_prof <- round(prof/sum(prof)*100, digits=1)
porcentagem_prof

lbls <- paste0(porcentagem_prof,"% ", lbls) 
lbls

png(filename="graficos/AproximacaoProfessores.png", width = 800, height = 500, pointsize = 16)
par(bg = "bisque")

### Geração do gráfico tipo pizza (pie)
pie(prof, labels = lbls, edges = 100, angle = 45, col = c("red","darkviolet", "pink"), main = "Aproximacao dos Professores por meio de Midias Sociais")

dev.off()

